spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usedbookmarket?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: usedbookmarket_admin
    password: 123456
  resources:
    static-locations: file:${upload.file-path}
swagger2:
  enable: true
mybatis:
  mapper-locations: classpath:mapperxml/*.xml
  type-aliases-package: com.robin.usedbookmarketbackend.model
server:
  servlet:
    session:
      timeout: 10s

upload:
  file-path: D:/Documents/usedbookmarket-upload/
  file-url: http://localhost:8080/
